### PR TITLE
Breaking: add missingValue error

### LINKED ISSUE #66: namespace/name may has no value
https://runkit.com/embed/0uz0sdas965j

There are 2 things have to be fixed:

1. `parseStringToEnd` should throw if there is nothing to parse. (It's still possible to specify an empty string via `""`)
2. Stop using `hasOwnProperty` to check mandatory properties:
		https://github.com/openstyles/parse-usercss/blob/e8d868dc222111bde0461f6c56b784f2d6ffe3be/lib/parse.js#L476

### PR DESCRIPTION
**Pull request by eight04**
Fixes #66.

### CODE REVIEW

**Comment by eight04** [comment]
@Mottie This change makes the var-text-empty test throw:
https://github.com/openstyles/usercss-meta/blob/e8d868dc222111bde0461f6c56b784f2d6ffe3be/tests/cases/var-text-empty/text.txt#L1-L3

Is this expected? Or should we allow variables without a default value?

**Comment by eight04** [comment]
I found this line in our spec:

> The default value for the variable. Having a default value is mandatory.

**Comment by Mottie** [comment]
Hmm, I don't think we should assume the default in that example is an empty string. It should throw an error.

**Comment by eight04** [comment]
The PR is ready.

**Comment by eight04** [comment]
Added an empty namespace test in 7eabf98.

**Pull request merged**
